# Generated by Django 5.1.5 on 2025-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_donators_wishlist_alter_mysavedproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysavedproduct',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mysavedproduct',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mysavedproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mysavedproduct',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
