# Generated by Django 5.1.5 on 2025-03-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_mysavedproduct_color_mysavedproduct_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donators',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donators',
            name='personal_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donators',
            name='rdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
