# Generated by Django 5.1.5 on 2025-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_mysavedproduct_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='donators',
            name='txn_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
