# Generated by Django 5.1.5 on 2025-03-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_pgrequest_user'),
        ('wishlist', '0007_donators_txn_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysavedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='orders.order'),
        ),
    ]
