# Generated by Django 5.1.5 on 2025-03-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_lenght_products_length'),
        ('wishlist', '0008_alter_mysavedproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysavedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='products.products'),
        ),
    ]
