# Generated by Django 5.1.5 on 2025-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('minPurchase', models.FloatField()),
                ('expiration', models.DateTimeField()),
                ('usageLimit', models.IntegerField()),
                ('usageCount', models.IntegerField()),
                ('applicableProducts', models.JSONField()),
                ('used_by', models.JSONField()),
                ('applicableCategories', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
