# Generated by Django 5.1.5 on 2025-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
