# Generated by Django 5.1.5 on 2025-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_register', '0002_alter_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user_type',
            field=models.CharField(default='vendor', max_length=255),
        ),
    ]
