# Generated by Django 5.1.5 on 2025-03-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
