# Generated by Django 5.1.5 on 2025-03-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_products_products_pr_search__c6bc8f_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.TextField()),
                ('hook_res_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transactionid', models.CharField(max_length=100)),
                ('hookdate', models.DateTimeField(auto_now_add=True)),
                ('hook_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('shipping', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(unique=True)),
                ('card_name', models.CharField(max_length=50)),
                ('exp_month', models.CharField(max_length=7)),
                ('exp_year', models.CharField(max_length=7)),
                ('first6', models.CharField(max_length=7)),
                ('bank', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PGRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('refid', models.CharField(blank=True, max_length=100, null=True)),
                ('txn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('customeremail', models.EmailField(max_length=254)),
                ('hook_res_id', models.CharField(blank=True, max_length=50, null=True)),
                ('res_status', models.CharField(blank=True, max_length=50, null=True)),
                ('callback_body', models.TextField()),
                ('hook_verified', models.BooleanField(default=False)),
                ('hook_check', models.BooleanField(default=False)),
                ('reqhash', models.CharField(blank=True, max_length=50, null=True)),
                ('contribute_code', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_message', models.TextField()),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.usercards')),
            ],
        ),
    ]
