# Generated by Django 5.1.5 on 2025-03-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgrequest',
            old_name='customeremail',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='pgrequest',
            old_name='hook_verified',
            new_name='delete_flag',
        ),
        migrations.RenameField(
            model_name='pgrequest',
            old_name='refid',
            new_name='ref_id',
        ),
        migrations.AddField(
            model_name='pgrequest',
            name='txn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pgrequest',
            name='callback_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgrequest',
            name='personal_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgrequest',
            name='res_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pgrequest',
            name='txn_type',
            field=models.CharField(choices=[('DONATION', 'Donation'), ('CHECKOUT', 'Checkout')], default='CHECKOUT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pgrequest',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.usercards'),
        ),
    ]
