# Generated by Django 5.1.5 on 2025-02-11 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_title_productcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='admin_act_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='admin_action',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='buyer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='cprice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='last_updated_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='moddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='preprice',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='products',
            name='product_brand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_feature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='rdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='shipping_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
