# Generated by Django 5.1.5 on 2025-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_price_products_admin_act_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_1_cloud_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_1_cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_1_pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_1_thumb_url',
            field=models.ImageField(blank=True, null=True, upload_to='_static/images/products/1/thumb/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2_cloud_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2_cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2_pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2_thumb_url',
            field=models.ImageField(blank=True, null=True, upload_to='_static/images/products/2/thumb/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3_cloud_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3_cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3_pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3_thumb_url',
            field=models.ImageField(blank=True, null=True, upload_to='_static/images/products/3/thumb/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_4_cloud_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_4_cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_4_pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_4_thumb_url',
            field=models.ImageField(blank=True, null=True, upload_to='_static/images/products/4/thumb/'),
        ),
    ]
