# Generated by Django 5.1.5 on 2025-02-19 12:34

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_image_1_thumb_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
