# Generated by Django 5.1.5 on 2025-02-19 12:36

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='products',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_pr_search__c6bc8f_gin'),
        ),
    ]
