# Generated by Django 5.1.5 on 2025-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_products_pr_search__c6bc8f_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='breadth',
            field=models.FloatField(default=0.025),
        ),
        migrations.AddField(
            model_name='products',
            name='lenght',
            field=models.FloatField(default=0.025),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.FloatField(default=0.025),
        ),
    ]
