# Generated by Django 5.1.5 on 2025-03-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_breadth_products_lenght_products_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='breadth',
            new_name='height',
        ),
    ]
