# Generated by Django 5.1.5 on 2025-03-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_breadth_products_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='lenght',
            new_name='length',
        ),
    ]
